### ISSUE TITLE
demo编译出错

### ISSUE THREAD

**Issue by guonaihong** [chai2010/logger#1]
hi, 柴神。
看到你的包组织结构很有意思，现在现在在写一个库coreutils，也想实现既可以是库，也可以编译成一个可执行文件的效果。
但是报错了，就想知道你是怎么玩的？
` env GOPATH=`pwd` go build -tags "ignore" github.com/chai2010/logger `
`can't load package: package github.com/chai2010/logger: found packages logger (example_test.go) and main (hello.go) in /home/guo/src/github.com/chai2010/logger`

**Comment by chai2010** [comment]
目前的Go语言对main包做了限制，只有`go test`可以导入main包，但是普通的包是不能导入main包的（Go的编译工具做了限制，语言并没有限制）。
这个包只有3个文件，logger是第一个包，测试部分是logger_test包（必须是_tast后缀才行，否则必须是logger），然后hello是main包。

hello.go的开头有`// +build ignore`， 因此平时是不编译的。
看你的命令后加了`-tags "ignore"`参数，这种做法应该是需要避免的，否则会导致main和logger包名不一致。

**Comment by guonaihong** [comment]
刚刚也试过go test
`
env GOPATH=`pwd` go test -tags "ignore"  -v github.com/chai2010/logger/
can't load package: package github.com/chai2010/logger: found packages logger (example_test.go) and main (hello.go) in /home/guo/src/github.com/chai2010/logger
`
柴神的意思是，高版本的go编译器，已经不能把main 包和其它包放到一个目录下编译了？如果是这样，我就不尝试把lib 包和main包放在一个包里面。

**Comment by chai2010** [comment]
同一个目录下同时只能有一个包被编译，test部分开了一个特权
